before_install:
 - pip install --upgrade pip wheel
language: python
cache: apt
sudo: false
python:
 - '3.4'
install:
 - pip install requests
 - pip install json
script:
 - python fetch.py > decodex_data.json
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
